### ISSUE TITLE
Live demo link of portfolio page

### ISSUE THREAD

**Issue by PinkMoon25** [PinkMoon25/Portfolio#7]
Hi, as I had previously deployed the page from the main branch, here is the link to my portfolio page https://pinkmoon25.github.io/Portfolio/ 
Thank you for the review

**Comment by mikethreels** [comment]
Hi Tushar, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PinkMoon25** [comment]
Thank you @mikethreels
